// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"lusionhouse-server/app/controller/user"
	"lusionhouse-server/app/infrastructure/repository"
	user2 "lusionhouse-server/app/service/user"
)

// Injectors from wire.go:

func InitUserController(name string) *user.LoginController {
	userRepository := repository.NewUserRepository()
	userServiceIml := user2.NewUserService(userRepository)
	loginController := user.NewUserController(userServiceIml)
	return loginController
}
